### ISSUE TITLE
tunnel问题

### ISSUE THREAD

**Issue by fshh1988** [b23r0/rsocx#3]
服务器运行xsocks -t -p1 8085 -p2 8086
远程客户端运行xsocks -r x.x.x.x:8085
本地客户端运行proxifier全局代理
使用20多分钟后就无法转发代理
下面是proxifier测试代理：
[50:09] 测试已开始。
    代理服务器
    地址: x.x.x.x:8086
    协议: SOCKS 5
    验证: 是
    用户名:  xxx

[50:09] 正在开始: 测试 1: 连接到代理服务器
[50:09] IP 地址: x.x.x.x
[50:09] 已建立连接
[50:09] 测试已通过。
[50:09] 正在开始: 测试 2: 通过代理服务器连接
转发不过去，求解

**Comment by 5loyd** [comment]
谢谢。这是一个Bug。我会在最近修复。

**Comment by vaselo** [comment]
Any updates?
