### ISSUE TITLE
makefile:10: recipe for target 'src/Tunnel.o' failed

### ISSUE THREAD

**Issue by 1c3z** [b23r0/rsocx#5]
% make
g++     -c  src/Tunnel.cpp    -o   src/Tunnel.o    -I./src -DLINUX 
In file included from src/Tunnel.cpp:1:0:
src/stdafx.h:13:15: error: redeclaration of C++ built-in type ‘bool’ [-fpermissive]
  typedef bool bool;
               ^
src/stdafx.h:24:14: error: multiple types in one declaration
  typedef int int;
              ^
src/stdafx.h:24:14: error: declaration does not declare anything [-fpermissive]
In file included from src/stdafx.h:53:0,
                 from src/Tunnel.cpp:1:
src/utils/AutoCleanup.h:105:38: warning: converting to non-pointer type ‘DWORD {aka long unsigned int}’ from NULL [-Wconversion-null]
  bool WaitForEnd(DWORD dwTimeoutMS = INFINITE)
                                      ^
src/utils/AutoCleanup.h: In constructor ‘Thread::Thread()’:
src/utils/AutoCleanup.h:68:19: warning: converting to non-pointer type ‘HANDLE {aka long unsigned int}’ from NULL [-Wconversion-null]
   , m_dwThreadId(0)
                   ^
src/utils/AutoCleanup.h: In destructor ‘Thread::~Thread()’:
src/utils/AutoCleanup.h:74:15: warning: NULL used in arithmetic [-Wpointer-arith]
   if (NULL != m_hThread) 
               ^
src/utils/AutoCleanup.h: In member function ‘bool Thread::Start(LPTHREAD_START_ROUTINE, LPVOID)’:
src/utils/AutoCleanup.h:84:15: warning: NULL used in arithmetic [-Wpointer-arith]
   if (NULL != m_hThread) return FALSE;
               ^
src/utils/AutoCleanup.h: In member function ‘bool Thread::WaitForEnd(DWORD)’:
src/utils/AutoCleanup.h:107:15: warning: NULL used in arithmetic [-Wpointer-arith]
   if (NULL == m_hThread) return TRUE;
               ^
src/utils/AutoCleanup.h:118:22: warning: NULL used in arithmetic [-Wpointer-arith]
   if (dwTimeoutMS == INFINITE)
                      ^
src/utils/AutoCleanup.h:131:14: warning: converting to non-pointer type ‘HANDLE {aka long unsigned int}’ from NULL [-Wconversion-null]
    m_hThread = NULL;
              ^
src/utils/AutoCleanup.h: In member function ‘void Thread::Terminate()’:
src/utils/AutoCleanup.h:148:13: warning: converting to non-pointer type ‘HANDLE {aka long unsigned int}’ from NULL [-Wconversion-null]
   m_hThread = NULL;
             ^
In file included from src/stdafx.h:56:0,
                 from src/Tunnel.cpp:1:
src/socks/SocksParser.h: At global scope:
src/common/CommonDefines.h:19:3: error: ‘BOOL’ does not name a type
   BOOL Init();       \
   ^
src/socks/SocksParser.h:38:2: note: in expansion of macro ‘DECLARE_SINGLETON’
  DECLARE_SINGLETON(SocksParser)
  ^
src/common/CommonDefines.h:19:3: error: ‘BOOL’ does not name a type
   BOOL Init();       \
   ^
src/Tunnel.h:27:2: note: in expansion of macro ‘DECLARE_SINGLETON’
  DECLARE_SINGLETON(CTunnel)
  ^
src/Tunnel.cpp: In member function ‘DWORD CTunnel::TCPTunnelProc(LPVOID)’:
src/Tunnel.cpp:214:16: warning: converting to non-pointer type ‘DWORD {aka long unsigned int}’ from NULL [-Wconversion-null]
  t1.WaitForEnd();
                ^
src/Tunnel.cpp:215:16: warning: converting to non-pointer type ‘DWORD {aka long unsigned int}’ from NULL [-Wconversion-null]
  t2.WaitForEnd();
                ^
src/Tunnel.cpp: In member function ‘bool CTunnel::Begin(int, int)’:
src/Tunnel.cpp:247:16: warning: converting to non-pointer type ‘DWORD {aka long unsigned int}’ from NULL [-Wconversion-null]
  t1.WaitForEnd();
                ^
src/Tunnel.cpp:248:16: warning: converting to non-pointer type ‘DWORD {aka long unsigned int}’ from NULL [-Wconversion-null]
  t2.WaitForEnd();
                ^
makefile:10: recipe for target 'src/Tunnel.o' failed
make: **\* [src/Tunnel.o] Error 1

编译环境
Linux #27-Ubuntu SMP Thu Dec 17 22:57:08 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
gcc version 5.2.1 20151010 (Ubuntu 5.2.1-22ubuntu2)

**Comment by howmp** [comment]
src/stdafx.h中有两行需要修改
typedef bool bool 修改为 typedef bool BOOL
typedef int int 删掉

makefile中
$(CC)     -c  $<    -o   $@    -I./src -DLINUX $(DEBUG) -fpermissive

最后不要忘记要新建bin目录

**Comment by go-spider** [comment]
还要在根目录下新建一个bin文件夹
