### ISSUE TITLE
Using reverse proxy function

### ISSUE THREAD

**Issue by Flavius01** [b23r0/rsocx#6]
Hi, and thank you for contributing that socks5 project on github! I was just looking for a very simple cmdline proxy to learn with, and yours seems perfect for this.

However, I have a problem using the reverse proxy function. Maybe I'm doing something wrong, or there's a bug.

This is the scenario: 1 remote machine connects via reverse proxy to my local machine. I want then to connect my Firefox browser to the local proxy on my machine.

1) On my local Windows10 machine (IP address 192.168.1.46), I want to place the local proxy server, which will route connections from the reverse proxy machine.  On this local machine I open xsocks using tunneling command:

```
xsocks -t -p1 2404 -p2 2405

[+] BIND PORTS 2404 AND 2405...
[+] LISTENING...
```

2) On my Windows7 machine in LAN, I place xsocks proxy in reverse mode:

```
xsocks -r  192.168.1.46:2404

[+] CONNECTING 192.168.1.46:2404
[+] CONNECT SUCCESS!
```

3) Finally, I connect Firefox to my local proxy, so 127.0.0.1:2405.

However, it doesn't manage to connect. When I use a normal forward proxy on my remote machine, on an open port, it works correctly though.
Is there a bug, or am I doing something wrong?

Thanks!!

**Comment by Neosama** [comment]
I have the same worries.
